train:
  max_epoch: 200
  save_epoch: 20
  shot: 1
  query: 15
  train_way: 30
  test_way: 5
  datasets: "mini-imageNet"
  datapath: '/data/songk/project/work'
  save_path: 'exps/exp-v1/proto'
  gpu: 'gpu:0'
  seed: 17206
  lr: 0.001
  stepSize: 20
  gamma: 0.5
test:
  gpu: 'gpu:0'
  load: 'exps/exp-v1/proto/max-acc.pth'
  datapath: '/data/songk/project/work'
  result: 'exps/exp-v1/proto/result'
  batch: 2000
  way: 5
  shot: 1
  query: 30
  seed: 17206
